<?php

/**
 * @file
 * Contains girchi_leaderboard.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function girchi_leaderboard_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the girchi_leaderboard module.
    case 'help.page.girchi_leaderboard':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Girchi leaderboard') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function girchi_leaderboard_theme() {
  return [
    'lead_partners' => [
      'variables' =>
        [
          'leadPartner' => NULL,
          'leadPartnerDaily' => NULL,
          'leadPartnerWeekly' => NULL,
          'leadPartnerMonthly' => NULL,
        ],
      'template' => 'lead-partners',
    ],
  ];
}
