<?php

/**
 * @file
 * Girchi paypal module.
 */

/**
 * Theme.
 *
 * @inheritDoc
 */
function girchi_paypal_theme() {
  return [
    'girchi_donations_paypal' => [
      'render element' => 'children',
      'variables' => [
        'status' => NULL,
        'amount' => NULL,
        'auth' => NULL,
      ],
    ],
    'girchi_donations_denied' => [
      'render element' => 'children',
    ],
  ];
}
