<?php

/**
 * @file
 * Girchi paypal module.
 */

/**
 * Theme.
 *
 * @inheritDoc
 */
function girchi_paypal_theme() {
  return [
    'girchi_donations_paypal' => [
      'render element' => 'children',
      'variables' => [
        'status' => NULL,
        'amount' => NULL,
        'auth' => NULL,
      ],
    ],
    'girchi_donations_denied' => [
      'render element' => 'children',
    ],
  ];
}

/**
 * Hook_library_info_alter.
 *
 * @inheritDoc
 */
function girchi_paypal_library_info_alter(&$libraries, $extension) {
  if ($extension == 'girchi' && ($libraries['donation'])) {
    $paypal_config = \Drupal::config('girchi_paypal.paypalsettings');
    $client_id = $paypal_config->get('client_id');
    $paypal_library = sprintf('https://www.paypal.com/sdk/js?client-id=%s&disable-funding=credit,card', $client_id);
    $attributes = ["type" => "external", "minified" => TRUE];
    $libraries['donation']['js'][$paypal_library] = $attributes;
  }
}
