<?php

/**
 * @file
 * Contains girchi_my_party_list.module.
 */

use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function girchi_my_party_list_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the girchi_my_party_list module.
    case 'help.page.girchi_my_party_list':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Module for my party list form') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function girchi_my_party_list_theme() {
  return [
    'girchi_my_party_list' => [
      'render element' => 'children',
      'variables' => [
        'my_party_list' => NULL,
        'max_percentage' => NULL,
        'top_politicians' => NULL,
      ],
    ],
    'girchi_party_list' => [
      'variables' => [
        'supporters' => NULL,
      ],
    ],
    'politician_rating_block' => [
      'variables' => [
        'politicians' => NULL,
      ],
    ],
  ];
}

/**
 * Implements hook_form_alter().
 */
function girchi_my_party_list_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  if ($form_id == 'views_exposed_form') {
    $form['combine']['#attributes']['class'][] = 'border-0 py-1 m-1 px-3 outline-none font-size-3 text-success w-100';
    $form['combine']['#attributes']['placeholder'] = t('Search...');
    $form['#attributes']['class'][] = 'w-100 max-w-md-200 pt-3  mt-2 mt-md-0 pt-md-0 navbar-search ml-auto text-right';
  }

}

/**
 * Implements hook_cron().
 */
function girchi_my_party_list_cron() {
  /**
   * @var \Drupal\girchi_my_party_list\PartyListCalculatorService $party_list_calculator
   */
  $party_list_calculator = Drupal::service('girchi_my_party_list.party_list_calculator');
  $party_list_calculator->calculate();
}

/**
 * Implements hook_user_presave().
 */
function girchi_my_party_list_user_presave(EntityInterface $user) {
  if ($user->original->get('field_politician')->value == 1 && $user->get('field_politician')->value == 0) {
    $user->set('field_political_ged', 0);
    $user->set('field_rating_in_party_list', NULL);
    $user_storage = Drupal::entityTypeManager()->getStorage('user');
    $user_ids = $user_storage
      ->getQuery()
      ->condition('field_ged', '0', '>')
      ->condition('field_my_party_list', $user->id(), 'IN')
      ->execute();
    if (!empty($user_ids)) {
      $users = $user_storage->loadMultiple($user_ids);
      foreach ($users as $supporter) {
        $supporter_party_list = $supporter->get('field_my_party_list')->getValue();
        $key = array_search($user->id(), array_column($supporter_party_list, 'target_id'));
        $supporter->get('field_my_party_list')->removeItem((int) $key);
        $supporter->save();
      }
    }
  }
}
